ALTER TABLE BOOKS ADD BESTSELLER BOOLEAN;

DROP PROCEDURE IF EXISTS UpdateBestsellers;

DELIMITER $$

CREATE PROCEDURE UpdateBestsellers()
BEGIN
    DECLARE RENTNUMBER, BESTSELLER_ID INT;
    DECLARE FINISHED INT DEFAULT 0;
    DECLARE ALL_BOOKS CURSOR FOR SELECT BOOK_ID FROM BOOKS;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;
    OPEN ALL_BOOKS;
    WHILE (FINISHED = 0) DO

            IF (RENTNUMBER >= 2) THEN
                UPDATE BOOKS SET BESTSELLER = TRUE
                WHERE BOOK_ID = BESTSELLER_ID;
            ELSE
                UPDATE BOOKS SET BESTSELLER = FALSE
                WHERE BOOK_ID = BESTSELLER_ID;
            END IF;

            FETCH ALL_BOOKS INTO BESTSELLER_ID;
            IF (FINISHED = 0) THEN
                SELECT COUNT(*) FROM RENTS
                WHERE BOOK_ID = BESTSELLER_ID
                INTO RENTNUMBER;
            END IF;
            COMMIT;
        END WHILE;

    CLOSE ALL_BOOKS;
END $$

DELIMITER ;

CALL UpdateBestsellers();

SELECT * FROM BOOKS;