CREATE TABLE STATS (
    STAT_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    STAT_DATE DATETIME NOT NULL,
    STAT VARCHAR(20) NOT NULL,
    VALUE INT(11) NOT NULL
);

CREATE VIEW BESTSELLERS_COUNT AS
SELECT COUNT(*)
FROM BOOKS
WHERE BESTSELLER = TRUE;

USE KODILLA_COURSE;

DELIMITER $$

CREATE EVENT UPDATE_STATS
    ON SCHEDULE EVERY 1 MINUTE
    DO
    BEGIN
        CALL UpdateVipLevels();
        INSERT INTO STATS (STAT_DATE, STAT, VALUE)
        VALUE (CURTIME(), "BESTSELLERS", (SELECT * FROM  BESTSELLERS_COUNT));
    END $$

DELIMITER ;

SELECT  * FROM STATS;

DROP EVENT UPDATE_STATS;