EXPLAIN SELECT COUNT(*)
        FROM READERS
        WHERE FIRSTNAME = "John";

CREATE INDEX READERSNO ON READERS (FIRSTNAME, LASTNAME);

EXPLAIN SELECT COUNT(*)
        FROM READERS
        WHERE FIRSTNAME = "John";

CREATE INDEX BOOKSNO ON BOOKS (TITLE);